export const queryKey = {
  WORKSPACE_PROFILE: 'workspace_profile',
  WORKSPACE_TEAMS: 'workspace_teams',
  WORKSPACE_MEMBERS: 'workspace_members',
  MY_PROFILE: 'my_profile',
  GITHUB_LINK: 'github_link',
  GOAL_NAME: 'goal_name',
  GOAL_DETAIL: 'goal_detail',
  GOAL_LIST: 'goal_list',
  GOAL_LIST_SIMPLE: 'goal_list_simple',
  ISSUE_NAME: 'issue_name',
  ISSUE_LIST: 'issue_list',
  ISSUE_LIST_SIMPLE: 'issue_list_simple',
  NOTI_LIST: 'noti_list',
  EXTERNAL_NAME: 'external_name',
  EXTERNAL_LINKS: 'external_links',
  EXTERNAL_SIMPLE_ISSUE: 'external_simple_issue',
  EXTERNAL_LIST: 'external_list',
  TEAM_MEMBER_LIST: 'team_member_list',
  GITHUB_REPOSITORIES: 'github_repositories',
  GITHUB_INSTALLATION_ID: 'github_installation_id',
  COMMENT_LIST: 'comment_list',
};
